// filepath: /home/julian/Documents/Workspace/portfolio/main-vargasdev/wrangler.toml
name = "main-vargasdev"
compatibility_date = "2025-07-21"

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
workers_dev = true